### ISSUE TITLE
DesignTime data for XAML Previewer

### ISSUE THREAD

**Issue by JasonColeyNZ** [rid00z/FreshMvvm#143]
Is there any way to have design time data, so that I can use the XAML Previewer to design my forms?

**Comment by rid00z** [comment]
Yes.
http://motzcod.es/post/143702671962/xamarinforms-xaml-previewer-design-time-data

**Comment by JasonColeyNZ** [comment]
yeah I tried that but it didn't work for me, I am new however... I kind of managed to get gorilla viewer going sort of OK, still having issues with custom controls, but close

**Comment by codegrue** [comment]
@rid00z Reading the link you provided. Since FreshMvvm automatically wires up the viewmodel as the bindingcontext, where do you inject an override to use the design time viewmodel instead?

**Comment by codegrue** [comment]
The technique in the referenced article doesn't distinguish between design time data and run time data. Assuming you want to use the same ViewModel, I think you want to inject it with a set of mock data. The problem I see is the model binding and IOC stuff doesn't actually run in the XAML previewer, so all of the automatic binding is out the window. My solution was to put this in the page.cs:

```
if (IsDesignMode)
{
    BindingContext = new PageViewModel(new MockDataService());
}

```
Where the constructor is my viewmodel looks like this:

```
private IDataService _dataService;

public BoatListViewModel(IDataService dataService)
{
    _dataService = dataService;
}
```

And my IOC wiring (in App.cs), which only gets used at runtime, is:

`FreshIOC.Container.Register<IDataService, DataService>();`

Im not in love with this methodology, since I still have duplicate code on every page codebehind, and pieces are kind of spread out. But I like reusing the same viewmodel only injecting with different data sets depending on mode.

P.S. IsDesignTime is not build into Xamarin, you have to derive that yourself.
