### ISSUE TITLE
ResolvePageModel throws Exception if Page and/or ViewModel are in "sub" namespaces

### ISSUE THREAD

**Issue by t4lm1d** [rid00z/FreshMvvm#149]
When calling FreshMvvm.FreshPageModelResolver.ResolvePageModel<WelcomeViewModel>(), the page cannot be resolved (the view/page model resolves) unless both the page and the page/view model are in the root namespace.  Is this desired functionality?

ex.

These resolve:
namespace CSI
{
	public partial class WelcomePage : ContentPage
	{
        public WelcomePage()
        {
            InitializeComponent();
        }
       }
}

namespace CSI
{
	public class WelcomeViewModel : FreshBasePageModel
	{
        public WelcomeViewModel()
        {
            
        }
	}
}

The Page does NOT resolve:
namespace CSI.ViewModel
{
	public partial class WelcomePage : ContentPage
	{
        public WelcomePage()
        {
            InitializeComponent();
        }
       }
}

namespace CSI (or changing this namespace)
{
	public class WelcomeViewModel : FreshBasePageModel
	{
        public WelcomeViewModel()
        {
            
        }
	}
}

**Comment by WiteCastle** [comment]
I've had issues with the ViewModel naming conventions. Could you try to rename the classes and namespace with PageModel and see if that helps?

**Comment by t4lm1d** [comment]
For now I put everything at the root.  As soon as I get to a place where I can pause, I'll see if the error goes away with a name change.

**Comment by agarbutt** [comment]
@WiteCastle @t4lm1d FYI, the issue you are encountering is because of the simple approach to resolving page types from their page models.  
Have a look at [here](https://github.com/rid00z/FreshMvvm/blob/b513917c75e0a718fe4df3eddd269cce1c9090b3/src/FreshMvvm/FreshPageModelMapper.cs#L11) and you will see if you place your page models / view models in a name space with the word "ViewModel" or "PageModel" it will be replace with the word "Page" and therefore the type resolution will fail.

Seems like picking any other namespace naming convention should work.   Best of luck.

**Comment by t4lm1d** [comment]
@WiteCastle Thanks!  I haven't had time to look into this so I appreciate your response.  Seeing that link you sent, makes sense.  I will close this issue.
