### ISSUE TITLE
Ready for use in production?

### ISSUE THREAD

**Issue by wcoder** [rid00z/FreshMvvm#26]
Hi Michael

Do you use FreshMvvm in the production? Is he ready for this?

**Comment by jfversluis** [comment]
Hi @wcoder 

I've used FreshMvvm in two production apps now without major problems.
While developing there are still some quirks, or maybe that's because I'm doing something wrong ;-)

Also I'm running into some trouble with Windows Phone, but also there I'm not sure if that is an error on my part. I yet have to figure that out.

Are there any particular situations you are looking for?

**Comment by wcoder** [comment]
Hi @jfversluis 

Thanks for your answer.

No, while I have no particular situations.

Currently I investigate opportunities for using FreshMvvm in production. At first glance, the framework very good, I found it very useful. Especially interesting current problems and how much of a charge from its developers for further support.

**Comment by rid00z** [comment]
Hi @wcoder 

I've been using it in production for 18 months in 5+ projects.

**Comment by wcoder** [comment]
Hi @rid00z 

That is great!

Thanks for answer.
