### ISSUE TITLE
BottomTabbedPage

### ISSUE THREAD

**Issue by swapnil591** [rid00z/FreshMvvm#260]
How to change position of tabbed page from top to bottom.

**Comment by libin85** [comment]
to change the tabbed position to the bottom has got nothing to do with FreshMvvm. Page Check the tabbed page documentation within xamarin forms and it has all the relevant code for u. But if you have tried and have any issues that caused by FreshMvvm , please let us with more information and we can look into it.

**Comment by twenzel** [comment]
It works for me.

In `App.xaml.cs`:
```
var tabbedNavigation = new FreshTabbedNavigationContainer();
tabbedNavigation.On<Xamarin.Forms.PlatformConfiguration.Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);
tabbedNavigation.AddTab<xyPageModel>("xy", "xy.png");
tabbedNavigation.AddTab<yyyyPageModel>("yyy", "yyyy.png");
tabbedNavigation.AddTab<cccPageModel>("ccc", "cccc.png");            

MainPage = loginStack;
```
