### ISSUE TITLE
PopPageModel not works on Android if I push PageModel from ViewIsAppearing

### ISSUE THREAD

**Issue by Josecanalla** [rid00z/FreshMvvm#273]
I have a Xamarin.Forms app.

If I do this from ViewIsAppearing method of FirstPageModel:

`CoreMethods.PushPageModel<SecondPageModel>();`

Then, when I am in the "SecondPageModel" if I do CoreMethods.PopPageModel(); not works in Android (anything happens). And if I press back button (I am using FreshMasterDetailNavigationContainer) anything happens.

In iOS it works OK.

**Comment by libin85** [comment]
Its pretty hard to tell what exactly is happening. Firstly I personally don't think its a great idea to do another navigation in the ViewIsAppearing. Its because your current page is just getting loaded onto the screen and  if the navigation to the second page is called  before the first page loads, the navigation stack is empty and the pop will not work. Sounds like thats the issue here.

**Comment by rid00z** [comment]
@Josecanalla I agree with @libin85, navigating on ViewIsAppearing is not the best idea. It would be ideal to rework your code to avoid this. Closing this for now but feel free to re-open if you need more help.
