### ISSUE TITLE
Proper cleanup of Pages

### ISSUE THREAD

**Issue by escamoteur** [rid00z/FreshMvvm#42]
Hi,

I think there should be a way to clean up events and the releasing of the binding context when a page is popped.

I included a destructor in FreshBasePageModel

       ~FreshBasePageModel()
        {
            var page = CurrentPage;
            page.BindingContext = null;

            page.Appearing -= ViewIsAppearing;
            page.Disappearing -= ViewIsDisappearing;

        }

But I'm not sure if this would be enough as we don'r know when it will be called.
What do you think?

**Comment by percramer** [comment]
Hi,

i would like to know also what the best place is to do some cleanup. The reverse init doesn't hold a reference to the closed page, so that doesn't work for me. I need to do some cleanup at some point and unsubscribe from some message centre events. I can't use the appearing / disappearing events because i don't need to clean up on a disappear event, i only need to clean up when the actual page is popped.

Regards,

Per

**Comment by rid00z** [comment]
PageModel now have a Popped event.
