### ISSUE TITLE
Can't add tab without an icon

### ISSUE THREAD

**Issue by chrbir** [rid00z/FreshMvvm#9]
I get an "Argument null exception" error if I use null as the icon parameter in the FreshTabbedNavigationContainers, AddTab.

If I use whitespace, UIKit.UIImage gives me another error.

The example here uses "null", http://goo.gl/AvlBbO
Maybe it's a change in Xamarin that courses this issue?

**Comment by rid00z** [comment]
Are you using this from nuget?

**Comment by Chrisbii** [comment]
Yes.

**Comment by MBrekhof** [comment]
Same problem/issue here

**Comment by rid00z** [comment]
@MBrekhof 
The code looks ok and it seems to be working on for me. Can you provide a sample reproduction app?

**Comment by MBrekhof** [comment]
Hi Michael,
Sorry for not reacting any sooner. It's been kind of busy at the moment.
As for the problem, this code was giving the problem:
     public class App : Application
     {
         public App()
         {
FreshIOC.Container.Register<IDatabaseService,DatabaseService>();
             var tabbedNavigation = new FreshTabbedNavigationContainer();
tabbedNavigation.AddTab<InboxListPageModel>("Inboxen", null);
tabbedNavigation.AddTab<WerkmapListPageModel>("Taken", null);

             MainPage = tabbedNavigation;
         }

However I upgrade to Forms 1.5.1.... (from 1.3.3...) and can not 
reproduce the problem anymore ;-).

Not sure if this makes any sense but at least the problem is gone.

While I have your attention: is is possible to programmatically 
enable/disable one or more tabs during run-time?

regards
Martin

ps. I really like  FreshMvvm, simple and yet powerfull

Op 20-10-2015 om 12:19 schreef Michael Ridland:
